using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GasyTek.ProductService.Migrations
{
    public partial class Initial : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Products",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Title = table.Column<string>(type: "text", nullable: true),
                    Description = table.Column<string>(type: "text", nullable: true),
                    Price = table.Column<double>(type: "double precision", nullable: false),
                    DiscountPercentage = table.Column<double>(type: "double precision", nullable: false),
                    Rating = table.Column<double>(type: "double precision", nullable: false),
                    Stock = table.Column<int>(type: "integer", nullable: false),
                    Brand = table.Column<string>(type: "text", nullable: true),
                    Category = table.Column<string>(type: "text", nullable: true),
                    Thumbnail = table.Column<string>(type: "text", nullable: true),
                    Images = table.Column<string[]>(type: "text[]", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Products", x => x.Id);
                });

            migrationBuilder.InsertData(
                table: "Products",
                columns: new[] { "Id", "Brand", "Category", "Description", "DiscountPercentage", "Images", "Price", "Rating", "Stock", "Thumbnail", "Title" },
                values: new object[,]
                {
                    { 1, "Apple", "smartphones", "An apple mobile which is nothing like apple", 12.960000000000001, new[] { "https://i.dummyjson.com/data/products/1/1.jpg", "https://i.dummyjson.com/data/products/1/2.jpg", "https://i.dummyjson.com/data/products/1/3.jpg", "https://i.dummyjson.com/data/products/1/4.jpg", "https://i.dummyjson.com/data/products/1/thumbnail.jpg" }, 549.0, 4.6900000000000004, 94, "https://i.dummyjson.com/data/products/1/thumbnail.jpg", "iPhone 9" },
                    { 2, "Apple", "smartphones", "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...", 17.940000000000001, new[] { "https://i.dummyjson.com/data/products/2/1.jpg", "https://i.dummyjson.com/data/products/2/2.jpg", "https://i.dummyjson.com/data/products/2/3.jpg", "https://i.dummyjson.com/data/products/2/thumbnail.jpg" }, 899.0, 4.4400000000000004, 34, "https://i.dummyjson.com/data/products/2/thumbnail.jpg", "iPhone X" },
                    { 3, "Samsung", "smartphones", "Samsung's new variant which goes beyond Galaxy to the Universe", 15.460000000000001, new[] { "https://i.dummyjson.com/data/products/3/1.jpg" }, 1249.0, 4.0899999999999999, 36, "https://i.dummyjson.com/data/products/3/thumbnail.jpg", "Samsung Universe 9" },
                    { 4, "OPPO", "smartphones", "OPPO F19 is officially announced on April 2021.", 17.91, new[] { "https://i.dummyjson.com/data/products/4/1.jpg", "https://i.dummyjson.com/data/products/4/2.jpg", "https://i.dummyjson.com/data/products/4/3.jpg", "https://i.dummyjson.com/data/products/4/4.jpg", "https://i.dummyjson.com/data/products/4/thumbnail.jpg" }, 280.0, 4.2999999999999998, 123, "https://i.dummyjson.com/data/products/4/thumbnail.jpg", "OPPOF19" },
                    { 5, "Huawei", "smartphones", "Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.", 10.58, new[] { "https://i.dummyjson.com/data/products/5/1.jpg", "https://i.dummyjson.com/data/products/5/2.jpg", "https://i.dummyjson.com/data/products/5/3.jpg" }, 499.0, 4.0899999999999999, 32, "https://i.dummyjson.com/data/products/5/thumbnail.jpg", "Huawei P30" },
                    { 6, "Apple", "laptops", "MacBook Pro 2021 with mini-LED display may launch between September, November", 11.02, new[] { "https://i.dummyjson.com/data/products/6/1.png", "https://i.dummyjson.com/data/products/6/2.jpg", "https://i.dummyjson.com/data/products/6/3.png", "https://i.dummyjson.com/data/products/6/4.jpg" }, 1749.0, 4.5700000000000003, 83, "https://i.dummyjson.com/data/products/6/thumbnail.png", "MacBook Pro" },
                    { 7, "Samsung", "laptops", "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched", 4.1500000000000004, new[] { "https://i.dummyjson.com/data/products/7/1.jpg", "https://i.dummyjson.com/data/products/7/2.jpg", "https://i.dummyjson.com/data/products/7/3.jpg", "https://i.dummyjson.com/data/products/7/thumbnail.jpg" }, 1499.0, 4.25, 50, "https://i.dummyjson.com/data/products/7/thumbnail.jpg", "Samsung Galaxy Book" },
                    { 8, "Microsoft Surface", "laptops", "Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen.", 10.23, new[] { "https://i.dummyjson.com/data/products/8/1.jpg", "https://i.dummyjson.com/data/products/8/2.jpg", "https://i.dummyjson.com/data/products/8/3.jpg", "https://i.dummyjson.com/data/products/8/4.jpg", "https://i.dummyjson.com/data/products/8/thumbnail.jpg" }, 1499.0, 4.4299999999999997, 68, "https://i.dummyjson.com/data/products/8/thumbnail.jpg", "Microsoft Surface Laptop 4" },
                    { 9, "Infinix", "laptops", "Infinix Inbook X1 Ci3 10th 8GB 256GB 14 Win10 Grey – 1 Year Warranty", 11.83, new[] { "https://i.dummyjson.com/data/products/9/1.jpg", "https://i.dummyjson.com/data/products/9/2.png", "https://i.dummyjson.com/data/products/9/3.png", "https://i.dummyjson.com/data/products/9/4.jpg", "https://i.dummyjson.com/data/products/9/thumbnail.jpg" }, 1099.0, 4.54, 96, "https://i.dummyjson.com/data/products/9/thumbnail.jpg", "Infinix INBOOK" },
                    { 10, "HP Pavilion", "laptops", "HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5, 8GB, 256GB SSD, GTX 1650 4GB, Windows 10", 6.1799999999999997, new[] { "https://i.dummyjson.com/data/products/10/1.jpg", "https://i.dummyjson.com/data/products/10/2.jpg", "https://i.dummyjson.com/data/products/10/3.jpg", "https://i.dummyjson.com/data/products/10/thumbnail.jpeg" }, 1099.0, 4.4299999999999997, 89, "https://i.dummyjson.com/data/products/10/thumbnail.jpeg", "HP Pavilion 15-DK1056WM" },
                    { 11, "Impression of Acqua Di Gio", "fragrances", "Mega Discount, Impression of Acqua Di Gio by GiorgioArmani concentrated attar perfume Oil", 8.4000000000000004, new[] { "https://i.dummyjson.com/data/products/11/1.jpg", "https://i.dummyjson.com/data/products/11/2.jpg", "https://i.dummyjson.com/data/products/11/3.jpg", "https://i.dummyjson.com/data/products/11/thumbnail.jpg" }, 13.0, 4.2599999999999998, 65, "https://i.dummyjson.com/data/products/11/thumbnail.jpg", "perfume Oil" },
                    { 12, "Royal_Mirage", "fragrances", "Royal_Mirage Sport Brown Perfume for Men & Women - 120ml", 15.66, new[] { "https://i.dummyjson.com/data/products/12/1.jpg", "https://i.dummyjson.com/data/products/12/2.jpg", "https://i.dummyjson.com/data/products/12/3.png", "https://i.dummyjson.com/data/products/12/4.jpg", "https://i.dummyjson.com/data/products/12/thumbnail.jpg" }, 40.0, 4.0, 52, "https://i.dummyjson.com/data/products/12/thumbnail.jpg", "Brown Perfume" },
                    { 13, "Fog Scent Xpressio", "fragrances", "Product details of Best Fog Scent Xpressio Perfume 100ml For Men cool long lasting perfumes for Men", 8.1400000000000006, new[] { "https://i.dummyjson.com/data/products/13/1.jpg", "https://i.dummyjson.com/data/products/13/2.png", "https://i.dummyjson.com/data/products/13/3.jpg", "https://i.dummyjson.com/data/products/13/4.jpg", "https://i.dummyjson.com/data/products/13/thumbnail.webp" }, 13.0, 4.5899999999999999, 61, "https://i.dummyjson.com/data/products/13/thumbnail.webp", "Fog Scent Xpressio Perfume" },
                    { 14, "Al Munakh", "fragrances", "Original Al Munakh® by Mahal Al Musk | Our Impression of Climate | 6ml Non-Alcoholic Concentrated Perfume Oil", 15.6, new[] { "https://i.dummyjson.com/data/products/14/1.jpg", "https://i.dummyjson.com/data/products/14/2.jpg", "https://i.dummyjson.com/data/products/14/3.jpg", "https://i.dummyjson.com/data/products/14/thumbnail.jpg" }, 120.0, 4.21, 114, "https://i.dummyjson.com/data/products/14/thumbnail.jpg", "Non-Alcoholic Concentrated Perfume Oil" },
                    { 15, "Lord - Al-Rehab", "fragrances", "Genuine  Al-Rehab spray perfume from UAE/Saudi Arabia/Yemen High Quality", 10.99, new[] { "https://i.dummyjson.com/data/products/15/1.jpg", "https://i.dummyjson.com/data/products/15/2.jpg", "https://i.dummyjson.com/data/products/15/3.jpg", "https://i.dummyjson.com/data/products/15/4.jpg", "https://i.dummyjson.com/data/products/15/thumbnail.jpg" }, 30.0, 4.7000000000000002, 105, "https://i.dummyjson.com/data/products/15/thumbnail.jpg", "Eau De Perfume Spray" },
                    { 16, "L'Oreal Paris", "skincare", "L'OrÃ©al Paris introduces Hyaluron Expert Replumping Serum formulated with 1.5% Hyaluronic Acid", 13.31, new[] { "https://i.dummyjson.com/data/products/16/1.png", "https://i.dummyjson.com/data/products/16/2.webp", "https://i.dummyjson.com/data/products/16/3.jpg", "https://i.dummyjson.com/data/products/16/4.jpg", "https://i.dummyjson.com/data/products/16/thumbnail.jpg" }, 19.0, 4.8300000000000001, 110, "https://i.dummyjson.com/data/products/16/thumbnail.jpg", "Hyaluronic Acid Serum" },
                    { 17, "Hemani Tea", "skincare", "Tea tree oil contains a number of compounds, including terpinen-4-ol, that have been shown to kill certain bacteria,", 4.0899999999999999, new[] { "https://i.dummyjson.com/data/products/17/1.jpg", "https://i.dummyjson.com/data/products/17/2.jpg", "https://i.dummyjson.com/data/products/17/3.jpg", "https://i.dummyjson.com/data/products/17/thumbnail.jpg" }, 12.0, 4.5199999999999996, 78, "https://i.dummyjson.com/data/products/17/thumbnail.jpg", "Tree Oil 30ml" },
                    { 18, "Dermive", "skincare", "Dermive Oil Free Moisturizer with SPF 20 is specifically formulated with ceramides, hyaluronic acid & sunscreen.", 13.1, new[] { "https://i.dummyjson.com/data/products/18/1.jpg", "https://i.dummyjson.com/data/products/18/2.jpg", "https://i.dummyjson.com/data/products/18/3.jpg", "https://i.dummyjson.com/data/products/18/4.jpg", "https://i.dummyjson.com/data/products/18/thumbnail.jpg" }, 40.0, 4.5599999999999996, 88, "https://i.dummyjson.com/data/products/18/thumbnail.jpg", "Oil Free Moisturizer 100ml" },
                    { 19, "ROREC White Rice", "skincare", "Product name: rorec collagen hyaluronic acid white face serum riceNet weight: 15 m", 10.68, new[] { "https://i.dummyjson.com/data/products/19/1.jpg", "https://i.dummyjson.com/data/products/19/2.jpg", "https://i.dummyjson.com/data/products/19/3.png", "https://i.dummyjson.com/data/products/19/thumbnail.jpg" }, 46.0, 4.4199999999999999, 54, "https://i.dummyjson.com/data/products/19/thumbnail.jpg", "Skin Beauty Serum." },
                    { 20, "Fair & Clear", "skincare", "Fair & Clear is Pakistan's only pure Freckle cream which helpsfade Freckles, Darkspots and pigments. Mercury level is 0%, so there are no side effects.", 16.989999999999998, new[] { "https://i.dummyjson.com/data/products/20/1.jpg", "https://i.dummyjson.com/data/products/20/2.jpg", "https://i.dummyjson.com/data/products/20/3.jpg", "https://i.dummyjson.com/data/products/20/4.jpg", "https://i.dummyjson.com/data/products/20/thumbnail.jpg" }, 70.0, 4.0599999999999996, 140, "https://i.dummyjson.com/data/products/20/thumbnail.jpg", "Freckle Treatment Cream- 15gm" },
                    { 21, "Saaf & Khaas", "groceries", "Fine quality Branded Product Keep in a cool and dry place", 4.8099999999999996, new[] { "https://i.dummyjson.com/data/products/21/1.png", "https://i.dummyjson.com/data/products/21/2.jpg", "https://i.dummyjson.com/data/products/21/3.jpg" }, 20.0, 4.4400000000000004, 133, "https://i.dummyjson.com/data/products/21/thumbnail.png", "- Daal Masoor 500 grams" },
                    { 22, "Bake Parlor Big", "groceries", "Product details of Bake Parlor Big Elbow Macaroni - 400 gm", 15.58, new[] { "https://i.dummyjson.com/data/products/22/1.jpg", "https://i.dummyjson.com/data/products/22/2.jpg", "https://i.dummyjson.com/data/products/22/3.jpg" }, 14.0, 4.5700000000000003, 146, "https://i.dummyjson.com/data/products/22/thumbnail.jpg", "Elbow Macaroni - 400 gm" },
                    { 23, "Baking Food Items", "groceries", "Specifications of Orange Essence Food Flavour For Cakes and Baking Food Item", 8.0399999999999991, new[] { "https://i.dummyjson.com/data/products/23/1.jpg", "https://i.dummyjson.com/data/products/23/2.jpg", "https://i.dummyjson.com/data/products/23/3.jpg", "https://i.dummyjson.com/data/products/23/4.jpg", "https://i.dummyjson.com/data/products/23/thumbnail.jpg" }, 14.0, 4.8499999999999996, 26, "https://i.dummyjson.com/data/products/23/thumbnail.jpg", "Orange Essence Food Flavou" },
                    { 24, "fauji", "groceries", "original fauji cereal muesli 250gm box pack original fauji cereals muesli fruit nuts flakes breakfast cereal break fast faujicereals cerels cerel foji fouji", 16.800000000000001, new[] { "https://i.dummyjson.com/data/products/24/1.jpg", "https://i.dummyjson.com/data/products/24/2.jpg", "https://i.dummyjson.com/data/products/24/3.jpg", "https://i.dummyjson.com/data/products/24/4.jpg", "https://i.dummyjson.com/data/products/24/thumbnail.jpg" }, 46.0, 4.9400000000000004, 113, "https://i.dummyjson.com/data/products/24/thumbnail.jpg", "cereals muesli fruit nuts" },
                    { 25, "Dry Rose", "groceries", "Dry Rose Flower Powder Gulab Powder 50 Gram • Treats Wounds", 13.58, new[] { "https://i.dummyjson.com/data/products/25/1.png", "https://i.dummyjson.com/data/products/25/2.jpg", "https://i.dummyjson.com/data/products/25/3.png", "https://i.dummyjson.com/data/products/25/4.jpg", "https://i.dummyjson.com/data/products/25/thumbnail.jpg" }, 70.0, 4.8700000000000001, 47, "https://i.dummyjson.com/data/products/25/thumbnail.jpg", "Gulab Powder 50 Gram" },
                    { 26, "Boho Decor", "home-decoration", "Boho Decor Plant Hanger For Home Wall Decoration Macrame Wall Hanging Shelf", 17.859999999999999, new[] { "https://i.dummyjson.com/data/products/26/1.jpg", "https://i.dummyjson.com/data/products/26/2.jpg", "https://i.dummyjson.com/data/products/26/3.jpg", "https://i.dummyjson.com/data/products/26/4.jpg", "https://i.dummyjson.com/data/products/26/5.jpg", "https://i.dummyjson.com/data/products/26/thumbnail.jpg" }, 41.0, 4.0800000000000001, 131, "https://i.dummyjson.com/data/products/26/thumbnail.jpg", "Plant Hanger For Home" },
                    { 27, "Flying Wooden", "home-decoration", "Package Include 6 Birds with Adhesive Tape Shape: 3D Shaped Wooden Birds Material: Wooden MDF, Laminated 3.5mm", 15.58, new[] { "https://i.dummyjson.com/data/products/27/1.jpg", "https://i.dummyjson.com/data/products/27/2.jpg", "https://i.dummyjson.com/data/products/27/3.jpg", "https://i.dummyjson.com/data/products/27/4.jpg", "https://i.dummyjson.com/data/products/27/thumbnail.webp" }, 51.0, 4.4100000000000001, 17, "https://i.dummyjson.com/data/products/27/thumbnail.webp", "Flying Wooden Bird" },
                    { 28, "LED Lights", "home-decoration", "3D led lamp sticker Wall sticker 3d wall art light on/off button  cell operated (included)", 16.489999999999998, new[] { "https://i.dummyjson.com/data/products/28/1.jpg", "https://i.dummyjson.com/data/products/28/2.jpg", "https://i.dummyjson.com/data/products/28/3.png", "https://i.dummyjson.com/data/products/28/4.jpg", "https://i.dummyjson.com/data/products/28/thumbnail.jpg" }, 20.0, 4.8200000000000003, 54, "https://i.dummyjson.com/data/products/28/thumbnail.jpg", "3D Embellishment Art Lamp" },
                    { 29, "luxury palace", "home-decoration", "Handcraft Chinese style art luxury palace hotel villa mansion home decor ceramic vase with brass fruit plate", 15.34, new[] { "https://i.dummyjson.com/data/products/29/1.jpg", "https://i.dummyjson.com/data/products/29/2.jpg", "https://i.dummyjson.com/data/products/29/3.webp", "https://i.dummyjson.com/data/products/29/4.webp", "https://i.dummyjson.com/data/products/29/thumbnail.webp" }, 60.0, 4.4400000000000004, 7, "https://i.dummyjson.com/data/products/29/thumbnail.webp", "Handcraft Chinese style" },
                    { 30, "Golden", "home-decoration", "Attractive DesignMetallic materialFour key hooksReliable & DurablePremium Quality", 2.9199999999999999, new[] { "https://i.dummyjson.com/data/products/30/1.jpg", "https://i.dummyjson.com/data/products/30/2.jpg", "https://i.dummyjson.com/data/products/30/3.jpg", "https://i.dummyjson.com/data/products/30/thumbnail.jpg" }, 30.0, 4.9199999999999999, 54, "https://i.dummyjson.com/data/products/30/thumbnail.jpg", "Key Holder" }
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Products");
        }
    }
}
