// <auto-generated />
using System;
using GasyTek.ProductService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GasyTek.ProductService.Migrations
{
    [DbContext(typeof(ProductsDbContext))]
    partial class ProductsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GasyTek.ProductService.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<double>("DiscountPercentage")
                        .HasColumnType("double precision");

                    b.Property<string[]>("Images")
                        .HasColumnType("text[]");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Apple",
                            Category = "smartphones",
                            Description = "An apple mobile which is nothing like apple",
                            DiscountPercentage = 12.960000000000001,
                            Images = new[] { "https://i.dummyjson.com/data/products/1/1.jpg", "https://i.dummyjson.com/data/products/1/2.jpg", "https://i.dummyjson.com/data/products/1/3.jpg", "https://i.dummyjson.com/data/products/1/4.jpg", "https://i.dummyjson.com/data/products/1/thumbnail.jpg" },
                            Price = 549.0,
                            Rating = 4.6900000000000004,
                            Stock = 94,
                            Thumbnail = "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
                            Title = "iPhone 9"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Apple",
                            Category = "smartphones",
                            Description = "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
                            DiscountPercentage = 17.940000000000001,
                            Images = new[] { "https://i.dummyjson.com/data/products/2/1.jpg", "https://i.dummyjson.com/data/products/2/2.jpg", "https://i.dummyjson.com/data/products/2/3.jpg", "https://i.dummyjson.com/data/products/2/thumbnail.jpg" },
                            Price = 899.0,
                            Rating = 4.4400000000000004,
                            Stock = 34,
                            Thumbnail = "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
                            Title = "iPhone X"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Samsung",
                            Category = "smartphones",
                            Description = "Samsung's new variant which goes beyond Galaxy to the Universe",
                            DiscountPercentage = 15.460000000000001,
                            Images = new[] { "https://i.dummyjson.com/data/products/3/1.jpg" },
                            Price = 1249.0,
                            Rating = 4.0899999999999999,
                            Stock = 36,
                            Thumbnail = "https://i.dummyjson.com/data/products/3/thumbnail.jpg",
                            Title = "Samsung Universe 9"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "OPPO",
                            Category = "smartphones",
                            Description = "OPPO F19 is officially announced on April 2021.",
                            DiscountPercentage = 17.91,
                            Images = new[] { "https://i.dummyjson.com/data/products/4/1.jpg", "https://i.dummyjson.com/data/products/4/2.jpg", "https://i.dummyjson.com/data/products/4/3.jpg", "https://i.dummyjson.com/data/products/4/4.jpg", "https://i.dummyjson.com/data/products/4/thumbnail.jpg" },
                            Price = 280.0,
                            Rating = 4.2999999999999998,
                            Stock = 123,
                            Thumbnail = "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
                            Title = "OPPOF19"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Huawei",
                            Category = "smartphones",
                            Description = "Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
                            DiscountPercentage = 10.58,
                            Images = new[] { "https://i.dummyjson.com/data/products/5/1.jpg", "https://i.dummyjson.com/data/products/5/2.jpg", "https://i.dummyjson.com/data/products/5/3.jpg" },
                            Price = 499.0,
                            Rating = 4.0899999999999999,
                            Stock = 32,
                            Thumbnail = "https://i.dummyjson.com/data/products/5/thumbnail.jpg",
                            Title = "Huawei P30"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Apple",
                            Category = "laptops",
                            Description = "MacBook Pro 2021 with mini-LED display may launch between September, November",
                            DiscountPercentage = 11.02,
                            Images = new[] { "https://i.dummyjson.com/data/products/6/1.png", "https://i.dummyjson.com/data/products/6/2.jpg", "https://i.dummyjson.com/data/products/6/3.png", "https://i.dummyjson.com/data/products/6/4.jpg" },
                            Price = 1749.0,
                            Rating = 4.5700000000000003,
                            Stock = 83,
                            Thumbnail = "https://i.dummyjson.com/data/products/6/thumbnail.png",
                            Title = "MacBook Pro"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Samsung",
                            Category = "laptops",
                            Description = "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
                            DiscountPercentage = 4.1500000000000004,
                            Images = new[] { "https://i.dummyjson.com/data/products/7/1.jpg", "https://i.dummyjson.com/data/products/7/2.jpg", "https://i.dummyjson.com/data/products/7/3.jpg", "https://i.dummyjson.com/data/products/7/thumbnail.jpg" },
                            Price = 1499.0,
                            Rating = 4.25,
                            Stock = 50,
                            Thumbnail = "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
                            Title = "Samsung Galaxy Book"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Microsoft Surface",
                            Category = "laptops",
                            Description = "Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen.",
                            DiscountPercentage = 10.23,
                            Images = new[] { "https://i.dummyjson.com/data/products/8/1.jpg", "https://i.dummyjson.com/data/products/8/2.jpg", "https://i.dummyjson.com/data/products/8/3.jpg", "https://i.dummyjson.com/data/products/8/4.jpg", "https://i.dummyjson.com/data/products/8/thumbnail.jpg" },
                            Price = 1499.0,
                            Rating = 4.4299999999999997,
                            Stock = 68,
                            Thumbnail = "https://i.dummyjson.com/data/products/8/thumbnail.jpg",
                            Title = "Microsoft Surface Laptop 4"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Infinix",
                            Category = "laptops",
                            Description = "Infinix Inbook X1 Ci3 10th 8GB 256GB 14 Win10 Grey – 1 Year Warranty",
                            DiscountPercentage = 11.83,
                            Images = new[] { "https://i.dummyjson.com/data/products/9/1.jpg", "https://i.dummyjson.com/data/products/9/2.png", "https://i.dummyjson.com/data/products/9/3.png", "https://i.dummyjson.com/data/products/9/4.jpg", "https://i.dummyjson.com/data/products/9/thumbnail.jpg" },
                            Price = 1099.0,
                            Rating = 4.54,
                            Stock = 96,
                            Thumbnail = "https://i.dummyjson.com/data/products/9/thumbnail.jpg",
                            Title = "Infinix INBOOK"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "HP Pavilion",
                            Category = "laptops",
                            Description = "HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5, 8GB, 256GB SSD, GTX 1650 4GB, Windows 10",
                            DiscountPercentage = 6.1799999999999997,
                            Images = new[] { "https://i.dummyjson.com/data/products/10/1.jpg", "https://i.dummyjson.com/data/products/10/2.jpg", "https://i.dummyjson.com/data/products/10/3.jpg", "https://i.dummyjson.com/data/products/10/thumbnail.jpeg" },
                            Price = 1099.0,
                            Rating = 4.4299999999999997,
                            Stock = 89,
                            Thumbnail = "https://i.dummyjson.com/data/products/10/thumbnail.jpeg",
                            Title = "HP Pavilion 15-DK1056WM"
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Impression of Acqua Di Gio",
                            Category = "fragrances",
                            Description = "Mega Discount, Impression of Acqua Di Gio by GiorgioArmani concentrated attar perfume Oil",
                            DiscountPercentage = 8.4000000000000004,
                            Images = new[] { "https://i.dummyjson.com/data/products/11/1.jpg", "https://i.dummyjson.com/data/products/11/2.jpg", "https://i.dummyjson.com/data/products/11/3.jpg", "https://i.dummyjson.com/data/products/11/thumbnail.jpg" },
                            Price = 13.0,
                            Rating = 4.2599999999999998,
                            Stock = 65,
                            Thumbnail = "https://i.dummyjson.com/data/products/11/thumbnail.jpg",
                            Title = "perfume Oil"
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Royal_Mirage",
                            Category = "fragrances",
                            Description = "Royal_Mirage Sport Brown Perfume for Men & Women - 120ml",
                            DiscountPercentage = 15.66,
                            Images = new[] { "https://i.dummyjson.com/data/products/12/1.jpg", "https://i.dummyjson.com/data/products/12/2.jpg", "https://i.dummyjson.com/data/products/12/3.png", "https://i.dummyjson.com/data/products/12/4.jpg", "https://i.dummyjson.com/data/products/12/thumbnail.jpg" },
                            Price = 40.0,
                            Rating = 4.0,
                            Stock = 52,
                            Thumbnail = "https://i.dummyjson.com/data/products/12/thumbnail.jpg",
                            Title = "Brown Perfume"
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Fog Scent Xpressio",
                            Category = "fragrances",
                            Description = "Product details of Best Fog Scent Xpressio Perfume 100ml For Men cool long lasting perfumes for Men",
                            DiscountPercentage = 8.1400000000000006,
                            Images = new[] { "https://i.dummyjson.com/data/products/13/1.jpg", "https://i.dummyjson.com/data/products/13/2.png", "https://i.dummyjson.com/data/products/13/3.jpg", "https://i.dummyjson.com/data/products/13/4.jpg", "https://i.dummyjson.com/data/products/13/thumbnail.webp" },
                            Price = 13.0,
                            Rating = 4.5899999999999999,
                            Stock = 61,
                            Thumbnail = "https://i.dummyjson.com/data/products/13/thumbnail.webp",
                            Title = "Fog Scent Xpressio Perfume"
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Al Munakh",
                            Category = "fragrances",
                            Description = "Original Al Munakh® by Mahal Al Musk | Our Impression of Climate | 6ml Non-Alcoholic Concentrated Perfume Oil",
                            DiscountPercentage = 15.6,
                            Images = new[] { "https://i.dummyjson.com/data/products/14/1.jpg", "https://i.dummyjson.com/data/products/14/2.jpg", "https://i.dummyjson.com/data/products/14/3.jpg", "https://i.dummyjson.com/data/products/14/thumbnail.jpg" },
                            Price = 120.0,
                            Rating = 4.21,
                            Stock = 114,
                            Thumbnail = "https://i.dummyjson.com/data/products/14/thumbnail.jpg",
                            Title = "Non-Alcoholic Concentrated Perfume Oil"
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Lord - Al-Rehab",
                            Category = "fragrances",
                            Description = "Genuine  Al-Rehab spray perfume from UAE/Saudi Arabia/Yemen High Quality",
                            DiscountPercentage = 10.99,
                            Images = new[] { "https://i.dummyjson.com/data/products/15/1.jpg", "https://i.dummyjson.com/data/products/15/2.jpg", "https://i.dummyjson.com/data/products/15/3.jpg", "https://i.dummyjson.com/data/products/15/4.jpg", "https://i.dummyjson.com/data/products/15/thumbnail.jpg" },
                            Price = 30.0,
                            Rating = 4.7000000000000002,
                            Stock = 105,
                            Thumbnail = "https://i.dummyjson.com/data/products/15/thumbnail.jpg",
                            Title = "Eau De Perfume Spray"
                        },
                        new
                        {
                            Id = 16,
                            Brand = "L'Oreal Paris",
                            Category = "skincare",
                            Description = "L'OrÃ©al Paris introduces Hyaluron Expert Replumping Serum formulated with 1.5% Hyaluronic Acid",
                            DiscountPercentage = 13.31,
                            Images = new[] { "https://i.dummyjson.com/data/products/16/1.png", "https://i.dummyjson.com/data/products/16/2.webp", "https://i.dummyjson.com/data/products/16/3.jpg", "https://i.dummyjson.com/data/products/16/4.jpg", "https://i.dummyjson.com/data/products/16/thumbnail.jpg" },
                            Price = 19.0,
                            Rating = 4.8300000000000001,
                            Stock = 110,
                            Thumbnail = "https://i.dummyjson.com/data/products/16/thumbnail.jpg",
                            Title = "Hyaluronic Acid Serum"
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Hemani Tea",
                            Category = "skincare",
                            Description = "Tea tree oil contains a number of compounds, including terpinen-4-ol, that have been shown to kill certain bacteria,",
                            DiscountPercentage = 4.0899999999999999,
                            Images = new[] { "https://i.dummyjson.com/data/products/17/1.jpg", "https://i.dummyjson.com/data/products/17/2.jpg", "https://i.dummyjson.com/data/products/17/3.jpg", "https://i.dummyjson.com/data/products/17/thumbnail.jpg" },
                            Price = 12.0,
                            Rating = 4.5199999999999996,
                            Stock = 78,
                            Thumbnail = "https://i.dummyjson.com/data/products/17/thumbnail.jpg",
                            Title = "Tree Oil 30ml"
                        },
                        new
                        {
                            Id = 18,
                            Brand = "Dermive",
                            Category = "skincare",
                            Description = "Dermive Oil Free Moisturizer with SPF 20 is specifically formulated with ceramides, hyaluronic acid & sunscreen.",
                            DiscountPercentage = 13.1,
                            Images = new[] { "https://i.dummyjson.com/data/products/18/1.jpg", "https://i.dummyjson.com/data/products/18/2.jpg", "https://i.dummyjson.com/data/products/18/3.jpg", "https://i.dummyjson.com/data/products/18/4.jpg", "https://i.dummyjson.com/data/products/18/thumbnail.jpg" },
                            Price = 40.0,
                            Rating = 4.5599999999999996,
                            Stock = 88,
                            Thumbnail = "https://i.dummyjson.com/data/products/18/thumbnail.jpg",
                            Title = "Oil Free Moisturizer 100ml"
                        },
                        new
                        {
                            Id = 19,
                            Brand = "ROREC White Rice",
                            Category = "skincare",
                            Description = "Product name: rorec collagen hyaluronic acid white face serum riceNet weight: 15 m",
                            DiscountPercentage = 10.68,
                            Images = new[] { "https://i.dummyjson.com/data/products/19/1.jpg", "https://i.dummyjson.com/data/products/19/2.jpg", "https://i.dummyjson.com/data/products/19/3.png", "https://i.dummyjson.com/data/products/19/thumbnail.jpg" },
                            Price = 46.0,
                            Rating = 4.4199999999999999,
                            Stock = 54,
                            Thumbnail = "https://i.dummyjson.com/data/products/19/thumbnail.jpg",
                            Title = "Skin Beauty Serum."
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Fair & Clear",
                            Category = "skincare",
                            Description = "Fair & Clear is Pakistan's only pure Freckle cream which helpsfade Freckles, Darkspots and pigments. Mercury level is 0%, so there are no side effects.",
                            DiscountPercentage = 16.989999999999998,
                            Images = new[] { "https://i.dummyjson.com/data/products/20/1.jpg", "https://i.dummyjson.com/data/products/20/2.jpg", "https://i.dummyjson.com/data/products/20/3.jpg", "https://i.dummyjson.com/data/products/20/4.jpg", "https://i.dummyjson.com/data/products/20/thumbnail.jpg" },
                            Price = 70.0,
                            Rating = 4.0599999999999996,
                            Stock = 140,
                            Thumbnail = "https://i.dummyjson.com/data/products/20/thumbnail.jpg",
                            Title = "Freckle Treatment Cream- 15gm"
                        },
                        new
                        {
                            Id = 21,
                            Brand = "Saaf & Khaas",
                            Category = "groceries",
                            Description = "Fine quality Branded Product Keep in a cool and dry place",
                            DiscountPercentage = 4.8099999999999996,
                            Images = new[] { "https://i.dummyjson.com/data/products/21/1.png", "https://i.dummyjson.com/data/products/21/2.jpg", "https://i.dummyjson.com/data/products/21/3.jpg" },
                            Price = 20.0,
                            Rating = 4.4400000000000004,
                            Stock = 133,
                            Thumbnail = "https://i.dummyjson.com/data/products/21/thumbnail.png",
                            Title = "- Daal Masoor 500 grams"
                        },
                        new
                        {
                            Id = 22,
                            Brand = "Bake Parlor Big",
                            Category = "groceries",
                            Description = "Product details of Bake Parlor Big Elbow Macaroni - 400 gm",
                            DiscountPercentage = 15.58,
                            Images = new[] { "https://i.dummyjson.com/data/products/22/1.jpg", "https://i.dummyjson.com/data/products/22/2.jpg", "https://i.dummyjson.com/data/products/22/3.jpg" },
                            Price = 14.0,
                            Rating = 4.5700000000000003,
                            Stock = 146,
                            Thumbnail = "https://i.dummyjson.com/data/products/22/thumbnail.jpg",
                            Title = "Elbow Macaroni - 400 gm"
                        },
                        new
                        {
                            Id = 23,
                            Brand = "Baking Food Items",
                            Category = "groceries",
                            Description = "Specifications of Orange Essence Food Flavour For Cakes and Baking Food Item",
                            DiscountPercentage = 8.0399999999999991,
                            Images = new[] { "https://i.dummyjson.com/data/products/23/1.jpg", "https://i.dummyjson.com/data/products/23/2.jpg", "https://i.dummyjson.com/data/products/23/3.jpg", "https://i.dummyjson.com/data/products/23/4.jpg", "https://i.dummyjson.com/data/products/23/thumbnail.jpg" },
                            Price = 14.0,
                            Rating = 4.8499999999999996,
                            Stock = 26,
                            Thumbnail = "https://i.dummyjson.com/data/products/23/thumbnail.jpg",
                            Title = "Orange Essence Food Flavou"
                        },
                        new
                        {
                            Id = 24,
                            Brand = "fauji",
                            Category = "groceries",
                            Description = "original fauji cereal muesli 250gm box pack original fauji cereals muesli fruit nuts flakes breakfast cereal break fast faujicereals cerels cerel foji fouji",
                            DiscountPercentage = 16.800000000000001,
                            Images = new[] { "https://i.dummyjson.com/data/products/24/1.jpg", "https://i.dummyjson.com/data/products/24/2.jpg", "https://i.dummyjson.com/data/products/24/3.jpg", "https://i.dummyjson.com/data/products/24/4.jpg", "https://i.dummyjson.com/data/products/24/thumbnail.jpg" },
                            Price = 46.0,
                            Rating = 4.9400000000000004,
                            Stock = 113,
                            Thumbnail = "https://i.dummyjson.com/data/products/24/thumbnail.jpg",
                            Title = "cereals muesli fruit nuts"
                        },
                        new
                        {
                            Id = 25,
                            Brand = "Dry Rose",
                            Category = "groceries",
                            Description = "Dry Rose Flower Powder Gulab Powder 50 Gram • Treats Wounds",
                            DiscountPercentage = 13.58,
                            Images = new[] { "https://i.dummyjson.com/data/products/25/1.png", "https://i.dummyjson.com/data/products/25/2.jpg", "https://i.dummyjson.com/data/products/25/3.png", "https://i.dummyjson.com/data/products/25/4.jpg", "https://i.dummyjson.com/data/products/25/thumbnail.jpg" },
                            Price = 70.0,
                            Rating = 4.8700000000000001,
                            Stock = 47,
                            Thumbnail = "https://i.dummyjson.com/data/products/25/thumbnail.jpg",
                            Title = "Gulab Powder 50 Gram"
                        },
                        new
                        {
                            Id = 26,
                            Brand = "Boho Decor",
                            Category = "home-decoration",
                            Description = "Boho Decor Plant Hanger For Home Wall Decoration Macrame Wall Hanging Shelf",
                            DiscountPercentage = 17.859999999999999,
                            Images = new[] { "https://i.dummyjson.com/data/products/26/1.jpg", "https://i.dummyjson.com/data/products/26/2.jpg", "https://i.dummyjson.com/data/products/26/3.jpg", "https://i.dummyjson.com/data/products/26/4.jpg", "https://i.dummyjson.com/data/products/26/5.jpg", "https://i.dummyjson.com/data/products/26/thumbnail.jpg" },
                            Price = 41.0,
                            Rating = 4.0800000000000001,
                            Stock = 131,
                            Thumbnail = "https://i.dummyjson.com/data/products/26/thumbnail.jpg",
                            Title = "Plant Hanger For Home"
                        },
                        new
                        {
                            Id = 27,
                            Brand = "Flying Wooden",
                            Category = "home-decoration",
                            Description = "Package Include 6 Birds with Adhesive Tape Shape: 3D Shaped Wooden Birds Material: Wooden MDF, Laminated 3.5mm",
                            DiscountPercentage = 15.58,
                            Images = new[] { "https://i.dummyjson.com/data/products/27/1.jpg", "https://i.dummyjson.com/data/products/27/2.jpg", "https://i.dummyjson.com/data/products/27/3.jpg", "https://i.dummyjson.com/data/products/27/4.jpg", "https://i.dummyjson.com/data/products/27/thumbnail.webp" },
                            Price = 51.0,
                            Rating = 4.4100000000000001,
                            Stock = 17,
                            Thumbnail = "https://i.dummyjson.com/data/products/27/thumbnail.webp",
                            Title = "Flying Wooden Bird"
                        },
                        new
                        {
                            Id = 28,
                            Brand = "LED Lights",
                            Category = "home-decoration",
                            Description = "3D led lamp sticker Wall sticker 3d wall art light on/off button  cell operated (included)",
                            DiscountPercentage = 16.489999999999998,
                            Images = new[] { "https://i.dummyjson.com/data/products/28/1.jpg", "https://i.dummyjson.com/data/products/28/2.jpg", "https://i.dummyjson.com/data/products/28/3.png", "https://i.dummyjson.com/data/products/28/4.jpg", "https://i.dummyjson.com/data/products/28/thumbnail.jpg" },
                            Price = 20.0,
                            Rating = 4.8200000000000003,
                            Stock = 54,
                            Thumbnail = "https://i.dummyjson.com/data/products/28/thumbnail.jpg",
                            Title = "3D Embellishment Art Lamp"
                        },
                        new
                        {
                            Id = 29,
                            Brand = "luxury palace",
                            Category = "home-decoration",
                            Description = "Handcraft Chinese style art luxury palace hotel villa mansion home decor ceramic vase with brass fruit plate",
                            DiscountPercentage = 15.34,
                            Images = new[] { "https://i.dummyjson.com/data/products/29/1.jpg", "https://i.dummyjson.com/data/products/29/2.jpg", "https://i.dummyjson.com/data/products/29/3.webp", "https://i.dummyjson.com/data/products/29/4.webp", "https://i.dummyjson.com/data/products/29/thumbnail.webp" },
                            Price = 60.0,
                            Rating = 4.4400000000000004,
                            Stock = 7,
                            Thumbnail = "https://i.dummyjson.com/data/products/29/thumbnail.webp",
                            Title = "Handcraft Chinese style"
                        },
                        new
                        {
                            Id = 30,
                            Brand = "Golden",
                            Category = "home-decoration",
                            Description = "Attractive DesignMetallic materialFour key hooksReliable & DurablePremium Quality",
                            DiscountPercentage = 2.9199999999999999,
                            Images = new[] { "https://i.dummyjson.com/data/products/30/1.jpg", "https://i.dummyjson.com/data/products/30/2.jpg", "https://i.dummyjson.com/data/products/30/3.jpg", "https://i.dummyjson.com/data/products/30/thumbnail.jpg" },
                            Price = 30.0,
                            Rating = 4.9199999999999999,
                            Stock = 54,
                            Thumbnail = "https://i.dummyjson.com/data/products/30/thumbnail.jpg",
                            Title = "Key Holder"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
